### ISSUE TITLE
End of the Project Checklist

### ISSUE THREAD

**Issue by A2va** [A2va/dai-qr-code#11]
- [x] Document multiple outputs in the README
- [x] Add QR Code to the README (maybe remove the current link)
- [x] Put the last commit on the original discussion: https://github.com/orgs/heig-vd-dai-course/discussions/397

Error Handling must be helpful
> The CLI displays a comprehensive help message on how to use the application and displays errors on invalid/missing inputs and/or processing errors
- [x] (Optional) Improve error handling by using a verbose flag to display the stacktrace, if not enabled a descriptive message will suffice

- [x] From the grading criteria, it seems that we must display the execution time of the program
> The CLI correctly processes the input file and writes the result in the output file with its execution time
